[package]
name = "duplicates_report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
sysinfo = "0.23.10"
fxhash = "0.2.1"
crossterm = "0.23.2"